import type { Collection, Note, Page, Paper } from '../types'

export const defaultCollections: Collection[] = [
  { id: 'machine-learning', name: '机器学习', color: '#63816d' },
  { id: 'language-models', name: '大语言模型', color: '#9b8ab8' },
  { id: 'design', name: '设计与人机交互', color: '#cf9b64' },
]
const examples = [
  [
    'Attention Is All You Need',
    'Ashish Vaswani et al.',
    2017,
    'NeurIPS',
    'machine-learning',
    ['Transformer', '深度学习'],
    'sage',
    'reading',
    'A new perspective on sequence modeling',
    'The Transformer is an architecture based on attention mechanisms. Instead of processing tokens one at a time through a recurrent state, it forms representations by attending to different positions in a sequence. This illustrative overview is written for the Paperead demo; import the original PDF to read the complete paper.',
    'The attention mechanism connects queries, keys, and values. Multiple attention heads can represent different relationships between tokens. Positional information makes it possible to distinguish ordering in the sequence.',
  ],
  [
    'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    'Patrick Lewis et al.',
    2020,
    'NeurIPS',
    'language-models',
    ['RAG', '自然语言处理'],
    'lavender',
    'unread',
    'Bringing external knowledge into generation',
    'Retrieval-augmented generation combines a generative language model with a retrieval system. Relevant passages are selected from a document collection and provided as context for an answer. This is an original demonstration summary, not the full paper.',
    'Separating stored knowledge from model parameters makes source material easier to update. Retrieval quality, context selection, and attribution all influence the reliability of the resulting response.',
  ],
  [
    'The Design of Everyday Things',
    'Donald A. Norman',
    2013,
    'Basic Books',
    'design',
    ['交互设计', '认知科学'],
    'sand',
    'reading',
    'Good design starts with understanding people',
    'This demonstration reading card explores discoverability and feedback in interface design. A useful interface helps people understand which actions are possible and makes the result of an action visible. This short original overview is not an excerpt from the book.',
    'Clear mappings and consistent constraints reduce the effort needed to learn a system. Errors offer opportunities to improve the design of the interaction rather than merely add more instructions.',
  ],
  [
    'Language Models are Few-Shot Learners',
    'Tom B. Brown et al.',
    2020,
    'NeurIPS',
    'language-models',
    ['LLM', 'In-context learning'],
    'blue',
    'finished',
    'Learning from examples in context',
    'A language model can be prompted with a task description and a small number of examples. This demonstration summary describes the idea of in-context learning without reproducing the source paper.',
    'The prompt specifies a pattern that the model is asked to continue. Results depend on task formulation, example selection, and evaluation methodology.',
  ],
  [
    'Denoising Diffusion Probabilistic Models',
    'Jonathan Ho et al.',
    2020,
    'NeurIPS',
    'machine-learning',
    ['Diffusion', '生成模型'],
    'rose',
    'unread',
    'Learning to reverse a gradual noise process',
    'Diffusion models use a sequence of denoising steps to produce a sample. This original demo overview introduces the relationship between a forward noise process and a learned reverse process.',
    'The forward process progressively perturbs data. A trained model estimates information required to reverse those perturbations, connecting a simple initial distribution with structured samples.',
  ],
  [
    'Human-Centered Artificial Intelligence',
    'Ben Shneiderman',
    2022,
    'Oxford University Press',
    'design',
    ['Human–AI', '可信 AI'],
    'olive',
    'unread',
    'Keeping people at the center of intelligent tools',
    'Human-centered AI considers how intelligent tools can support human goals and oversight. This Paperead demo summary is original explanatory text and is not the complete source work.',
    'Useful tools communicate limitations, expose meaningful controls, and provide feedback. Evaluation should consider the whole interaction and its consequences for the person using the system.',
  ],
] as const
const now = Date.now()
export const samplePapers: Paper[] = examples.map((e, i) => ({
  id: `sample-${i}`,
  hash: `sample-${i}`,
  title: e[0],
  authors: e[1],
  year: e[2],
  venue: e[3],
  collectionId: e[4],
  tags: [...e[5]],
  color: e[6],
  status: e[7],
  starred: i === 0 || i === 2,
  sample: true,
  currentPage: 1,
  pageCount: 2,
  createdAt: now - i * 86400000,
  lastReadAt: i === 0 ? now : now - i * 86400000,
  size: 0,
  abstract: e[9],
}))
export const samplePages: Page[] = examples.flatMap((e, i) => [
  {
    id: `sample-${i}:1`,
    paperId: `sample-${i}`,
    number: 1,
    text: `# ${e[0]}\n\n${e[1]} · ${e[2]}\n\n> 演示内容：以下为原创导读，并非原论文全文。请导入 PDF 阅读真实文献。\n\n## ${e[8]}\n\n${e[9]}\n\n## Key ideas\n\n${e[10]}\n\n### A note for your research\n\nSelect a passage to highlight it, attach an annotation, or turn your thoughts into a Markdown note. Your work stays on this device.`,
  },
  {
    id: `sample-${i}:2`,
    paperId: `sample-${i}`,
    number: 2,
    text: `# Reading questions\n\n## Reflect and connect\n\n- What is the central research question?\n- Which assumptions are essential to the method?\n- How could the findings connect to your own work?\n\n## Your next step\n\nImport the original PDF, inspect the methods and results, and record the evidence behind each conclusion.\n\n> 这是第二页演示导读，不代表原文内容。`,
  },
])
export const sampleNote: Note = {
  id: 'welcome-note',
  title: '从阅读到理解，建立自己的知识连接',
  paperId: 'sample-0',
  updatedAt: now,
  markdown:
    '# 从阅读到理解，建立自己的知识连接\n\n> 一篇论文的价值，不止于读完它。\n\n这是你的第一篇 Markdown 笔记。可以自由编辑，也可以导入已有的 `.md` 文件。\n\n## 阅读时，带着三个问题\n\n- **问题**：作者想解决什么？\n- **方法**：关键的想法和假设是什么？\n- **联系**：它与我的研究有什么关系？\n\n## 我的阅读计划\n\n- [x] 建立一个属于自己的文献库\n- [ ] 导入第一篇 PDF 论文\n- [ ] 记录一个值得继续探索的问题\n\n## 公式也能好好呈现\n\n$$\\mathrm{Attention}(Q,K,V)=\\mathrm{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$$\n\n---\n\n*在阅读器中选中一段文字，即可添加批注并收集到笔记。*',
}
